services:
  - type: web
    name: veefyed-admin
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist -l 10000
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
